Basic:
  task: ['docTquery']
  model_name: ['google-t5/t5-base']
  per_device_train_batch_size: [48]
  per_device_eval_batch_size: [16]
  evaluation_strategy: ['steps']
  run_name: ['docTquery-synthetic-T5b-50k']
  output_dir: ['../models/docTquery-synthetic-T5b-50k']
  learning_rate: [0.0001]
  warmup_steps: [10]
  max_steps: [500]
  max_length: [96]
  save_strategy: ['steps']
  train_file: ['../data/synthetics/syn_50k_train_d2q.json']
  valid_file: ['../data/synthetics/syn_50k_dev_d2q.json']
  dataloader_num_workers: [4]
  report_to: ['wandb']
  logging_steps: [5]
  eval_steps: [50]
  save_steps: [50]
  save_total_limit: [5]
  load_best_model_at_end: [1]
  gradient_accumulation_steps: [1]
  dataloader_drop_last: [0]