Basic:
  task: ['generation']
  model_name: ['google-t5/t5-base']
  model_path: ['../models/docTquery-synthetic-T5b-50k/checkpoint-500']
  per_device_eval_batch_size: [12]
  run_name: ['docTquery-synthetic-T5b-50k-gen']
  q_max_length: [64]
  max_length: [96]
  valid_file: ['../data/synthetics/syn_50k_seen_masked_clustered.tsv']
  output_dir: ['temp']
  dataloader_num_workers: [40]
  report_to: ['none']
  logging_steps: [100]
  top_k: [10]
  num_return_sequences: [5]